project_id = "labxxxrjmlxwngekosym"

[functions.seed-users]
verify_jwt = false

[functions.parse-document]
verify_jwt = false

[functions.match-clauses]
verify_jwt = false

[functions.process-approval-decision]
verify_jwt = true

[functions.check-tagging-prompt]
verify_jwt = true

[functions.submit-manual-tags]
verify_jwt = true

[functions.create-approvals-from-template]
verify_jwt = true

[functions.create-needs-from-template]
verify_jwt = true

[functions.generate-document]
verify_jwt = false
